version: "3"

volumes:
  node_modules:

services:
  frontend:
    build:
      context: ../
      dockerfile: ./Dockerfile
    tty: true
    stdin_open: true
    env_file:
      - ../.env
    ports:
      - "3000:3000"
    volumes:
      - ../:/app:delegated
      - node_modules:/app/node_modules
